In [29]:
import tensorflow as tf
from tensorflow import keras

In [30]:
print("Num Gpus Avaliable: ",len(tf.config.experimental.list_physical_devices("GPU")))

Num Gpus Avaliable:  1


In [31]:
tf.test.is_built_with_cuda()

True

In [32]:
tf.config.experimental.list_physical_devices("GPU")

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [33]:
print(tf.version.VERSION)

2.6.0


In [34]:
import sys
sys.version

'3.9.15 (main, Nov 24 2022, 14:39:17) [MSC v.1916 64 bit (AMD64)]'

In [35]:
from psutil import virtual_memory
ram_gb = virtual_memory().total / 1e9
print('Your runtime has {:.1f} gigabytes of available RAM\n'.format(ram_gb))

if ram_gb < 20:
  print('Not using a high-RAM runtime')
else:
  print('You are using a high-RAM runtime!')

Your runtime has 34.0 gigabytes of available RAM

You are using a high-RAM runtime!


In [36]:
if tf.test.gpu_device_name(): 

    print('Default GPU Device:{}'.format(tf.test.gpu_device_name()))

else:

   print("Please install GPU version of TF")

gpu_info = !nvidia-smi
gpu_info = '\n'.join(gpu_info)
if gpu_info.find('failed') >= 0:
  print('Not connected to a GPU')
else:
  print(gpu_info)


Default GPU Device:/device:GPU:0
Fri Mar 10 13:35:00 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 517.00       Driver Version: 517.00       CUDA Version: 11.7     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ... WDDM  | 00000000:01:00.0 Off |                  N/A |
| N/A   54C    P8    13W /  N/A |    309MiB / 16384MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                       

In [37]:
import numpy as np

In [38]:
def MultiplyVect(a,b,c):
    for i in range(a.size):
        c[i] = a[i]*b[i]
        

In [39]:
N = 64000000
A = np.ones(N,dtype = np.float32)
B = np.ones(N,dtype = np.float32) 
C = np.ones(N,dtype = np.float32)

In [40]:
%%time
MultiplyVect(A,B,C)

CPU times: total: 28.1 s
Wall time: 34.3 s


#Cupy

In [42]:
import cupy as cp

In [50]:
import numpy as np

In [56]:
list_cpu = np.random.randint(0,255, size = (2000,2000))

In [57]:
list_cpu

array([[ 30, 171, 119, ..., 108, 125, 201],
       [ 47,  46, 125, ...,  94,  22,  27],
       [ 14,  73, 133, ..., 206, 154, 184],
       ...,
       [  9,  47,  54, ..., 246, 163, 202],
       [ 18, 214,   7, ..., 145,  88, 246],
       [ 66, 227,  45, ..., 242, 198, 180]])

In [58]:
list_cpu.nbytes/1e6

16.0

In [59]:
list_gpu = cp.asarray(list_cpu)

In [60]:
list_gpu

array([[ 30, 171, 119, ..., 108, 125, 201],
       [ 47,  46, 125, ...,  94,  22,  27],
       [ 14,  73, 133, ..., 206, 154, 184],
       ...,
       [  9,  47,  54, ..., 246, 163, 202],
       [ 18, 214,   7, ..., 145,  88, 246],
       [ 66, 227,  45, ..., 242, 198, 180]])

In [63]:
%%timeit

list_gpu = cp.asarray(list_cpu)

2.39 ms ± 202 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [64]:
from scipy import fft

In [70]:
%%time

fft.fftn(list_cpu)

CPU times: total: 93.8 ms
Wall time: 168 ms


array([[ 5.07846218e+08     -0.j        ,
        -1.26155785e+05 +95035.53952556j,
         3.69822281e+04-102649.34863362j, ...,
         2.98457030e+03+192340.49124062j,
         3.69822281e+04+102649.34863362j,
        -1.26155785e+05 -95035.53952556j],
       [-4.48553552e+04  -5155.23924437j,
         1.08361276e+05 -44357.68506343j,
        -9.39989949e+04+177097.75742447j, ...,
         8.35742885e+04 +35358.9539537j ,
        -6.35518721e+02 -40638.40270254j,
         3.53542261e+04  -4173.81413861j],
       [-1.41053866e+05+165739.16091552j,
        -1.26007949e+05 -13810.15540392j,
         3.99190257e+04 -28125.69614712j, ...,
        -4.52363035e+04  +2551.65812785j,
         2.37147631e+04 +22298.23800118j,
         1.28097970e+05-176507.32769615j],
       ...,
       [ 1.50750030e+04 -62805.43643079j,
        -6.36307121e+04-135596.62090917j,
         6.36880655e+04 +20845.26565192j, ...,
         1.89620220e+04 -98458.18476066j,
         3.39131941e+04-114652.51851373j,

In [67]:
from cupyx.scipy import fft as fft_gpu

In [71]:
%%time

fft_gpu.fftn(list_gpu)

CPU times: total: 0 ns
Wall time: 1.56 ms


array([[ 5.07846218e+08     +0.j        ,
        -1.26155785e+05 +95035.53952556j,
         3.69822281e+04-102649.34863362j, ...,
         2.98457030e+03+192340.49124062j,
         3.69822281e+04+102649.34863362j,
        -1.26155785e+05 -95035.53952556j],
       [-4.48553552e+04  -5155.23924437j,
         1.08361276e+05 -44357.68506343j,
        -9.39989949e+04+177097.75742447j, ...,
         8.35742885e+04 +35358.9539537j ,
        -6.35518721e+02 -40638.40270254j,
         3.53542261e+04  -4173.81413861j],
       [-1.41053866e+05+165739.16091552j,
        -1.26007949e+05 -13810.15540392j,
         3.99190257e+04 -28125.69614712j, ...,
        -4.52363035e+04  +2551.65812785j,
         2.37147631e+04 +22298.23800118j,
         1.28097970e+05-176507.32769615j],
       ...,
       [ 1.50750030e+04 -62805.43643079j,
        -6.36307121e+04-135596.62090917j,
         6.36880655e+04 +20845.26565192j, ...,
         1.89620220e+04 -98458.18476066j,
         3.39131941e+04-114652.51851373j,

##communicating between cpu and gpu

In [74]:
 fft_cpu = fft.fftn(list_cpu)
    
fft_send_back = cp.asnumpy(fft_gpu.fftn(list_gpu))

np.allclose(fft_send_back,fft_cpu)

True