In [1]:
!pip install --upgrade jupyterlab-git

In [5]:
import tensorflow as tf
from tensorflow import keras

In [6]:
print("Num Gpus Avaliable: ",len(tf.config.experimental.list_physical_devices("GPU")))

Num Gpus Avaliable:  1


In [7]:
tf.test.is_built_with_cuda()

True

In [8]:
tf.config.experimental.list_physical_devices("GPU")

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [9]:
print(tf.version.VERSION)

2.6.0


In [10]:
import sys
sys.version

'3.9.15 (main, Nov 24 2022, 14:39:17) [MSC v.1916 64 bit (AMD64)]'

In [11]:
from psutil import virtual_memory
ram_gb = virtual_memory().total / 1e9
print('Your runtime has {:.1f} gigabytes of available RAM\n'.format(ram_gb))

if ram_gb < 20:
  print('Not using a high-RAM runtime')
else:
  print('You are using a high-RAM runtime!')

Your runtime has 34.0 gigabytes of available RAM

You are using a high-RAM runtime!


In [13]:
if tf.test.gpu_device_name(): 

    print('Default GPU Device:{}'.format(tf.test.gpu_device_name()))

else:

   print("Please install GPU version of TF")

gpu_info = !nvidia-smi
gpu_info = '\n'.join(gpu_info)
if gpu_info.find('failed') >= 0:
  print('Not connected to a GPU')
else:
  print(gpu_info)


Default GPU Device:/device:GPU:0
Sat Jun 10 23:05:03 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 517.00       Driver Version: 517.00       CUDA Version: 11.7     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ... WDDM  | 00000000:01:00.0 Off |                  N/A |
| N/A   44C    P8    11W /  N/A |    309MiB / 16384MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                       

In [14]:
import numpy as np

In [37]:
def MultiplyVect(a,b,c):
    for i in range(a.size):
        c[i] = a[i]*b[i]
        

In [38]:
N = 64000000
A = np.ones(N,dtype = np.float32)
B = np.ones(N,dtype = np.float32) 
C = np.ones(N,dtype = np.float32)

In [39]:
%%time
MultiplyVect(A,B,C)

CPU times: total: 3.3 s
Wall time: 9.48 s


#Cupy

In [18]:
import cupy as cp

In [19]:
import numpy as np

In [20]:
list_cpu = np.random.randint(0,255, size = (2000,2000))

In [21]:
list_cpu

array([[ 50,  87, 180, ...,  52, 239, 173],
       [ 58, 149,  30, ...,  63, 211, 236],
       [ 10,  78, 169, ..., 117, 241, 252],
       ...,
       [ 31, 207,  57, ..., 184, 134, 119],
       [134, 189, 249, ...,  37, 122, 104],
       [155, 200, 170, ..., 236, 225,  62]])

In [22]:
list_cpu.nbytes/1e6

16.0

In [23]:
list_gpu = cp.asarray(list_cpu)

In [24]:
list_gpu

array([[ 50,  87, 180, ...,  52, 239, 173],
       [ 58, 149,  30, ...,  63, 211, 236],
       [ 10,  78, 169, ..., 117, 241, 252],
       ...,
       [ 31, 207,  57, ..., 184, 134, 119],
       [134, 189, 249, ...,  37, 122, 104],
       [155, 200, 170, ..., 236, 225,  62]])

In [26]:
%%time

list_gpu = cp.asarray(list_cpu)

CPU times: total: 0 ns
Wall time: 1.96 ms


In [27]:
from scipy import fft

In [28]:
%%time

fft.fftn(list_cpu)

CPU times: total: 31.2 ms
Wall time: 96.9 ms


array([[ 5.07906863e+08     -0.j        ,
        -1.36726200e+05 -14177.8470709j ,
         3.81154702e+04 +47120.6237914j , ...,
        -2.98087187e+05 -17385.98984511j,
         3.81154702e+04 -47120.6237914j ,
        -1.36726200e+05 +14177.8470709j ],
       [ 2.03366748e+05  +1593.0112267j ,
         3.94872300e+04+130452.48732004j,
        -7.49202034e+04-135377.23025182j, ...,
         2.71231735e+05 -28276.03981786j,
         3.12895305e+04 -94741.49312452j,
         3.45307151e+04+132787.19052392j],
       [-1.03188232e+05 -78674.79547613j,
        -9.76308650e+03 +34809.62477082j,
        -1.07488112e+04 +45339.93076533j, ...,
        -1.30210719e+05 +77260.58103744j,
         5.14553644e+04-144817.60821698j,
         7.39551417e+04 +22306.99875882j],
       ...,
       [ 1.69853873e+05 +68411.02387495j,
         3.27223632e+04-142655.01460389j,
        -1.33951041e+05 -31964.30445874j, ...,
        -1.09646416e+05 +17742.7504347j ,
         1.63121395e+05+108956.64713614j,

In [30]:
from cupyx.scipy import fft as fft_gpu

In [31]:
%%time

fft_gpu.fftn(list_gpu)

CPU times: total: 125 ms
Wall time: 557 ms


array([[ 5.07906863e+08     +0.j        ,
        -1.36726200e+05 -14177.8470709j ,
         3.81154702e+04 +47120.62379139j, ...,
        -2.98087187e+05 -17385.98984511j,
         3.81154702e+04 -47120.62379139j,
        -1.36726200e+05 +14177.8470709j ],
       [ 2.03366748e+05  +1593.0112267j ,
         3.94872300e+04+130452.48732004j,
        -7.49202034e+04-135377.23025182j, ...,
         2.71231735e+05 -28276.03981786j,
         3.12895305e+04 -94741.49312452j,
         3.45307151e+04+132787.19052392j],
       [-1.03188232e+05 -78674.79547613j,
        -9.76308650e+03 +34809.62477082j,
        -1.07488112e+04 +45339.93076533j, ...,
        -1.30210719e+05 +77260.58103744j,
         5.14553644e+04-144817.60821698j,
         7.39551417e+04 +22306.99875882j],
       ...,
       [ 1.69853873e+05 +68411.02387495j,
         3.27223632e+04-142655.01460389j,
        -1.33951041e+05 -31964.30445874j, ...,
        -1.09646416e+05 +17742.7504347j ,
         1.63121395e+05+108956.64713614j,

##communicating between cpu and gpu

In [32]:
 fft_cpu = fft.fftn(list_cpu)
    
fft_send_back = cp.asnumpy(fft_gpu.fftn(list_gpu))

np.allclose(fft_send_back,fft_cpu)

True

#CUDA
link : https://numba.readthedocs.io/en/stable/cuda/kernels.html#kernel-invocation

In [33]:
from numba import cuda
import cupy as cp
import math

In [34]:
cuda.detect()

Found 1 CUDA devices
id 0    b'NVIDIA GeForce RTX 3080 Ti Laptop GPU'                              [SUPPORTED]
                      Compute Capability: 8.6
                           PCI Device ID: 0
                              PCI Bus ID: 1
                                    UUID: GPU-892b381c-02c1-7a90-1a6c-77164f75e2c2
                                Watchdog: Enabled
                            Compute Mode: WDDM
             FP32/FP64 Performance Ratio: 32
Summary:
	1/1 devices are supported


True

In [35]:
@cuda.jit
def increment_by_one(an_array):
    # Thread id in a 1D block
    tx = cuda.threadIdx.x
    # Block id in a 1D grid
    ty = cuda.blockIdx.x
    # Block width, i.e. number of threads per block
    bw = cuda.blockDim.x
    # Compute flattened index inside the array
    pos = tx + ty * bw
    if pos < an_array.size:  # Check array boundaries
        an_array[pos] += 1

In [36]:
@cuda.jit
def increment_by_one(an_array):
    pos = cuda.grid(1)
    if pos < an_array.size:
        an_array[pos] += 1


In [1]:
print("hello")

hello


In [3]:
import torch

In [4]:
torch.cuda.is_available()

True