In [1]:
!pip install --upgrade jupyterlab-git

In [1]:
import tensorflow as tf
from tensorflow import keras

In [2]:
print("Num Gpus Avaliable: ",len(tf.config.experimental.list_physical_devices("GPU")))

Num Gpus Avaliable:  1


In [3]:
tf.test.is_built_with_cuda()

True

In [4]:
tf.config.experimental.list_physical_devices("GPU")

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [5]:
print(tf.version.VERSION)

2.6.0


In [6]:
import sys
sys.version

'3.9.15 (main, Nov 24 2022, 14:39:17) [MSC v.1916 64 bit (AMD64)]'

In [7]:
from psutil import virtual_memory
ram_gb = virtual_memory().total / 1e9
print('Your runtime has {:.1f} gigabytes of available RAM\n'.format(ram_gb))

if ram_gb < 20:
  print('Not using a high-RAM runtime')
else:
  print('You are using a high-RAM runtime!')

Your runtime has 34.0 gigabytes of available RAM

You are using a high-RAM runtime!


In [8]:
if tf.test.gpu_device_name(): 

    print('Default GPU Device:{}'.format(tf.test.gpu_device_name()))

else:

   print("Please install GPU version of TF")

gpu_info = !nvidia-smi
gpu_info = '\n'.join(gpu_info)
if gpu_info.find('failed') >= 0:
  print('Not connected to a GPU')
else:
  print(gpu_info)


Default GPU Device:/device:GPU:0
Wed Mar 15 21:48:44 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 517.00       Driver Version: 517.00       CUDA Version: 11.7     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ... WDDM  | 00000000:01:00.0 Off |                  N/A |
| N/A   56C    P3    25W /  N/A |    309MiB / 16384MiB |      3%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                       

In [9]:
import numpy as np

In [10]:
def MultiplyVect(a,b,c):
    for i in range(a.size):
        c[i] = a[i]*b[i]
        

In [11]:
N = 64000000
A = np.ones(N,dtype = np.float32)
B = np.ones(N,dtype = np.float32) 
C = np.ones(N,dtype = np.float32)

In [12]:
%%time
MultiplyVect(A,B,C)

CPU times: total: 7.05 s
Wall time: 11.1 s


#Cupy

In [13]:
import cupy as cp

In [14]:
import numpy as np

In [15]:
list_cpu = np.random.randint(0,255, size = (2000,2000))

In [16]:
list_cpu

array([[230, 243,  58, ...,  71, 241, 246],
       [ 63,  20,  76, ...,  61,  28,  13],
       [ 98,  61, 118, ..., 148,  46, 166],
       ...,
       [ 68, 108, 231, ..., 113, 121, 114],
       [ 86, 218,  67, ..., 101, 182, 145],
       [178,  92,  19, ...,  82,   2,  95]])

In [17]:
list_cpu.nbytes/1e6

16.0

In [18]:
list_gpu = cp.asarray(list_cpu)

In [19]:
list_gpu

array([[230, 243,  58, ...,  71, 241, 246],
       [ 63,  20,  76, ...,  61,  28,  13],
       [ 98,  61, 118, ..., 148,  46, 166],
       ...,
       [ 68, 108, 231, ..., 113, 121, 114],
       [ 86, 218,  67, ..., 101, 182, 145],
       [178,  92,  19, ...,  82,   2,  95]])

In [20]:
%%timeit

list_gpu = cp.asarray(list_cpu)

2.64 ms ± 706 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [21]:
from scipy import fft

In [22]:
%%time

fft.fftn(list_cpu)

CPU times: total: 62.5 ms
Wall time: 93.8 ms


array([[ 5.08164471e+08     -0.j        ,
        -5.12243938e+04 -19062.74473907j,
        -4.96552773e+04-102940.61058228j, ...,
         9.59589323e+04 +75703.35376581j,
        -4.96552773e+04+102940.61058228j,
        -5.12243938e+04 +19062.74473907j],
       [-7.40785163e+03 -20761.46871025j,
         1.25199697e+05+312321.29811976j,
        -9.87023552e+04 -61033.52601258j, ...,
        -7.32628448e+03 +20540.77548966j,
        -2.23804849e+05 -30669.65510782j,
        -3.61716797e+04 -48444.03447903j],
       [ 2.35792705e+04 +21491.19742598j,
        -1.01443890e+05 +94721.4177104j ,
        -9.30742487e+04+144191.77355434j, ...,
         1.75309643e+05+198977.22832244j,
         2.96918639e+03 +86108.73986423j,
         4.20382456e+03 -56365.39337038j],
       ...,
       [-1.47675687e+05 -38484.90678535j,
        -4.25310301e+03 +91460.8721065j ,
        -1.93754718e+05+117583.04432408j, ...,
        -3.63709213e+02+167911.75628899j,
        -1.21291577e+04 -43578.45026875j,

In [23]:
from cupyx.scipy import fft as fft_gpu

In [24]:
%%time

fft_gpu.fftn(list_gpu)

CPU times: total: 188 ms
Wall time: 1.71 s


array([[ 5.08164471e+08     +0.j        ,
        -5.12243938e+04 -19062.74473907j,
        -4.96552773e+04-102940.61058228j, ...,
         9.59589323e+04 +75703.35376581j,
        -4.96552773e+04+102940.61058228j,
        -5.12243938e+04 +19062.74473907j],
       [-7.40785163e+03 -20761.46871025j,
         1.25199697e+05+312321.29811976j,
        -9.87023552e+04 -61033.52601258j, ...,
        -7.32628448e+03 +20540.77548966j,
        -2.23804849e+05 -30669.65510782j,
        -3.61716797e+04 -48444.03447903j],
       [ 2.35792705e+04 +21491.19742598j,
        -1.01443890e+05 +94721.4177104j ,
        -9.30742487e+04+144191.77355434j, ...,
         1.75309643e+05+198977.22832244j,
         2.96918639e+03 +86108.73986423j,
         4.20382456e+03 -56365.39337038j],
       ...,
       [-1.47675687e+05 -38484.90678535j,
        -4.25310301e+03 +91460.8721065j ,
        -1.93754718e+05+117583.04432408j, ...,
        -3.63709213e+02+167911.75628899j,
        -1.21291577e+04 -43578.45026875j,

##communicating between cpu and gpu

In [25]:
 fft_cpu = fft.fftn(list_cpu)
    
fft_send_back = cp.asnumpy(fft_gpu.fftn(list_gpu))

np.allclose(fft_send_back,fft_cpu)

True

#CUDA
link : https://numba.readthedocs.io/en/stable/cuda/kernels.html#kernel-invocation

In [48]:
from numba import cuda
import cupy as cp
import math

In [53]:
cuda.detect()

Found 1 CUDA devices
id 0    b'NVIDIA GeForce RTX 3080 Ti Laptop GPU'                              [SUPPORTED]
                      Compute Capability: 8.6
                           PCI Device ID: 0
                              PCI Bus ID: 1
                                    UUID: GPU-892b381c-02c1-7a90-1a6c-77164f75e2c2
                                Watchdog: Enabled
                            Compute Mode: WDDM
             FP32/FP64 Performance Ratio: 32
Summary:
	1/1 devices are supported


True

In [54]:
@cuda.jit
def increment_by_one(an_array):
    # Thread id in a 1D block
    tx = cuda.threadIdx.x
    # Block id in a 1D grid
    ty = cuda.blockIdx.x
    # Block width, i.e. number of threads per block
    bw = cuda.blockDim.x
    # Compute flattened index inside the array
    pos = tx + ty * bw
    if pos < an_array.size:  # Check array boundaries
        an_array[pos] += 1

In [ ]:
@cuda.jit
def increment_by_one(an_array):
    pos = cuda.grid(1)
    if pos < an_array.size:
        an_array[pos] += 1
