In [1]:
!pip install --upgrade jupyterlab-git

In [2]:
import tensorflow as tf
from tensorflow import keras

In [3]:
print("Num Gpus Avaliable: ",len(tf.config.experimental.list_physical_devices("GPU")))

Num Gpus Avaliable:  1


In [4]:
tf.test.is_built_with_cuda()

True

In [5]:
tf.config.experimental.list_physical_devices("GPU")

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [6]:
print(tf.version.VERSION)

2.6.0


In [7]:
import sys
sys.version

'3.9.15 (main, Nov 24 2022, 14:39:17) [MSC v.1916 64 bit (AMD64)]'

In [8]:
from psutil import virtual_memory
ram_gb = virtual_memory().total / 1e9
print('Your runtime has {:.1f} gigabytes of available RAM\n'.format(ram_gb))

if ram_gb < 20:
  print('Not using a high-RAM runtime')
else:
  print('You are using a high-RAM runtime!')

Your runtime has 34.0 gigabytes of available RAM

You are using a high-RAM runtime!


In [9]:
if tf.test.gpu_device_name(): 

    print('Default GPU Device:{}'.format(tf.test.gpu_device_name()))

else:

   print("Please install GPU version of TF")

gpu_info = !nvidia-smi
gpu_info = '\n'.join(gpu_info)
if gpu_info.find('failed') >= 0:
  print('Not connected to a GPU')
else:
  print(gpu_info)


Default GPU Device:/device:GPU:0
Sat May 13 20:52:50 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 517.00       Driver Version: 517.00       CUDA Version: 11.7     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ... WDDM  | 00000000:01:00.0 Off |                  N/A |
| N/A   50C    P0    27W /  N/A |    309MiB / 16384MiB |      2%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                       

In [12]:
import numpy as np

In [13]:
def MultiplyVect(a,b,c):
    for i in range(a.size):
        c[i] = a[i]*b[i]
        

In [14]:
N = 64000000
A = np.ones(N,dtype = np.float32)
B = np.ones(N,dtype = np.float32) 
C = np.ones(N,dtype = np.float32)

In [12]:
%%time
MultiplyVect(A,B,C)

CPU times: total: 7.05 s
Wall time: 11.1 s


#Cupy

In [19]:
import cupy as cp

In [20]:
import numpy as np

In [21]:
list_cpu = np.random.randint(0,255, size = (2000,2000))

In [22]:
list_cpu

array([[  8, 194, 119, ..., 125, 118, 106],
       [ 50, 129,  86, ...,   5, 220,  22],
       [ 82, 139,  24, ..., 144, 162, 164],
       ...,
       [171,  47, 253, ..., 139, 229,  26],
       [165, 189, 122, ..., 186,  85,  10],
       [ 18,  98, 158, ...,  11, 181,  14]])

In [26]:
list_cpu.nbytes/1e6

16.0

In [27]:
list_gpu = cp.asarray(list_cpu)

In [28]:
list_gpu

array([[  8, 194, 119, ..., 125, 118, 106],
       [ 50, 129,  86, ...,   5, 220,  22],
       [ 82, 139,  24, ..., 144, 162, 164],
       ...,
       [171,  47, 253, ..., 139, 229,  26],
       [165, 189, 122, ..., 186,  85,  10],
       [ 18,  98, 158, ...,  11, 181,  14]])

In [29]:
%%timeit

list_gpu = cp.asarray(list_cpu)

1.51 ms ± 100 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [30]:
from scipy import fft

In [31]:
%%time

fft.fftn(list_cpu)

CPU times: total: 31.2 ms
Wall time: 76.9 ms


array([[ 5.07937269e+08     -0.j        ,
        -1.77156125e+05 -34478.27514732j,
        -5.96031757e+04 -15215.33358875j, ...,
         2.38748078e+04 +93893.91261536j,
        -5.96031757e+04 +15215.33358875j,
        -1.77156125e+05 +34478.27514732j],
       [ 1.13964069e+05 -98048.5699259j ,
        -6.74948891e+04 +18873.89004452j,
         4.59862700e+04 +35675.71099994j, ...,
         6.39125234e+04+123186.51136109j,
         1.44164172e+04-138661.04652137j,
        -7.66928630e+04 -54615.42467222j],
       [-5.46022176e+04 +71290.26026384j,
        -2.26503769e+05 -27787.89026422j,
         9.70889191e+04 -45337.14160703j, ...,
         4.10279883e+04 -18224.74759131j,
        -2.75908193e+03-124335.44765277j,
        -9.68635384e+04 +98121.09325272j],
       ...,
       [ 4.38552036e+03 +41192.21735455j,
        -1.18987335e+03 +92152.3470731j ,
        -2.61726754e+04+155908.5367645j , ...,
        -1.62854836e+05  -2604.55486172j,
         1.36954494e+05 +31318.66293422j,

In [32]:
from cupyx.scipy import fft as fft_gpu

In [33]:
%%time

fft_gpu.fftn(list_gpu)

CPU times: total: 46.9 ms
Wall time: 576 ms


array([[ 5.07937269e+08     +0.j        ,
        -1.77156125e+05 -34478.27514732j,
        -5.96031757e+04 -15215.33358875j, ...,
         2.38748078e+04 +93893.91261536j,
        -5.96031757e+04 +15215.33358875j,
        -1.77156125e+05 +34478.27514732j],
       [ 1.13964069e+05 -98048.5699259j ,
        -6.74948891e+04 +18873.89004452j,
         4.59862700e+04 +35675.71099994j, ...,
         6.39125234e+04+123186.51136109j,
         1.44164172e+04-138661.04652137j,
        -7.66928630e+04 -54615.42467222j],
       [-5.46022176e+04 +71290.26026384j,
        -2.26503769e+05 -27787.89026422j,
         9.70889191e+04 -45337.14160703j, ...,
         4.10279883e+04 -18224.74759131j,
        -2.75908193e+03-124335.44765277j,
        -9.68635384e+04 +98121.09325272j],
       ...,
       [ 4.38552036e+03 +41192.21735455j,
        -1.18987335e+03 +92152.3470731j ,
        -2.61726754e+04+155908.5367645j , ...,
        -1.62854836e+05  -2604.55486172j,
         1.36954494e+05 +31318.66293422j,

##communicating between cpu and gpu

In [34]:
 fft_cpu = fft.fftn(list_cpu)
    
fft_send_back = cp.asnumpy(fft_gpu.fftn(list_gpu))

np.allclose(fft_send_back,fft_cpu)

True

#CUDA
link : https://numba.readthedocs.io/en/stable/cuda/kernels.html#kernel-invocation

In [35]:
from numba import cuda
import cupy as cp
import math

In [36]:
cuda.detect()

Found 1 CUDA devices
id 0    b'NVIDIA GeForce RTX 3080 Ti Laptop GPU'                              [SUPPORTED]
                      Compute Capability: 8.6
                           PCI Device ID: 0
                              PCI Bus ID: 1
                                    UUID: GPU-892b381c-02c1-7a90-1a6c-77164f75e2c2
                                Watchdog: Enabled
                            Compute Mode: WDDM
             FP32/FP64 Performance Ratio: 32
Summary:
	1/1 devices are supported


True

In [37]:
@cuda.jit
def increment_by_one(an_array):
    # Thread id in a 1D block
    tx = cuda.threadIdx.x
    # Block id in a 1D grid
    ty = cuda.blockIdx.x
    # Block width, i.e. number of threads per block
    bw = cuda.blockDim.x
    # Compute flattened index inside the array
    pos = tx + ty * bw
    if pos < an_array.size:  # Check array boundaries
        an_array[pos] += 1

In [40]:
@cuda.jit
def increment_by_one(an_array):
    pos = cuda.grid(1)
    if pos < an_array.size:
        an_array[pos] += 1


In [1]:
print("hello")

hello


In [3]:
import torch

In [4]:
torch.cuda.is_available()

True